name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:5.7
        options: --health-cmd="mysqladmin ping --silent" --health-interval=10s --health-timeout=5s --health-retries=3
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: symfony_test
        ports:
          - 3306:3306

    env:
      DATABASE_URL: mysql://root:root@127.0.0.1:3306/symfony_test

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.1'
        extensions: mbstring, intl, pdo_mysql
        tools: composer, phpunit, phpstan

    - name: Install Composer dependencies
      run: composer install --prefer-dist --no-progress --no-suggest --no-interaction

    - name: Create .env.test.local
      run: |
        echo 'DATABASE_URL="mysql://root:root@127.0.0.1:3306/symfony_test"' > .env.test.local

    - name: Run database migrations
      run: php bin/console doctrine:migrations:migrate --env=test --no-interaction

    - name: Run static analysis
      run: vendor/bin/phpstan analyse

    - name: Run unit tests
      run: vendor/bin/phpunit

    - name: Run security analysis
      run: symfony security:check
